name: "Get Artifact Id"
description: "Get the artifact id from the pom.xml file"
    
outputs:
  artifactId:
    description: get project (maven) artifactId
    value: ${{ steps.get-artifact-id.outputs.artifactId }}
    
runs:
  using: "composite"
  steps:
    - id: get-artifact-id
      name: Get artifactId
      shell: bash
      run: |
        artifactId=$(echo '${project.artifactId}' | mvn -N -q -DforceStdout help:evaluate)
        echo "::set-output name=artifactId::$artifactId"
